spring:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
#    generate-ddl: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/hotel
    username: root
    password: root

  application:
    name: hotel

  liquibase:
    enabled: true
    drop-first: false
    change-log: classpath:db/db-changelog-master.yaml
    default-schema: public
    contexts: migrated

server:
  port: 9095

